### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by freiburgermsu** [Fxe/cobrakbase#13]
Hello @Fxe !

I receive the attached error when I attempt to install the package. Is the error from an incompatible `numpy` version (I am operating the `numpy` version `1.23.5`) or the problem elsewhere?

Andrew

[cobrakbase_installation_errors.txt](https://github.com/Fxe/cobrakbase/files/10326615/cobrakbase_installation_errors.txt)

**Comment by freiburgermsu** [comment]
I remembered that this error is caused by mandating `scikit-learn==0.23.2` in the MSpy `setup.py` script. Changing this requirement to `scikit-learn>=0.23.2` resolves the bug without compromising the utility of code at this version level:

> "scikit-learn >= 0.23.2",  # too support KBase pickle models  # !!! The >= designation is necessary for Windows import

**Comment by Fxe** [comment]
This is a ModelSEEDpy issue because it requires an old version of `scikit-learn` (I think it is supported only for python <=3.8), we have to rebuild the ML models with a newer version but also the KBase App must be updated since the KBase pickles are made from that old version which complicates compatibility, if you do not need model reconstruction you can change to the latest `scikit-learn` until we update the ML models we can't change the version

**Comment by Fxe** [comment]
ML models updated to 1.2.0 this issue is solve, however ModelSEEDpy is now only supported by python >= 3.8
